### ISSUE TITLE
Some apps hang with muvm-x11bridge

### ISSUE THREAD

**Issue by whitebelyash** [AsahiLinux/muvm#124]
Some apps hang when running them in muvm with x11bridge. Does not happen with sommelier.

How to reproduce (with glxinfo for example):
1. Run muvm with x11bridge (`muvm -x` before b40bf03d2ce417b79b3cfec144a2681a92f9b46a)
2. Run `glxinfo -B`
3. Observe hang

Can also be reproduced with PrismLauncher when starting a Minecraft instance - launcher window hangs.  
Running it with strace gives this:
```
read(32, "name of display: :1\ndisplay: :1 "..., 4096) = 4096
read(32, "GL core profile profile mask: co"..., 4096) = 4096
read(32, 
```
Seems like it calls glxinfo which causes a hang.

Host: MacBook Air M1
OS: Fedora 41 GNOME (Asahi)
muvm: 0.1.4 (from asahi repos)

**Comment by alyssarosenzweig** [comment]
Hanging inside xshmfence 

```
#0  0x0000fffff7c561e4 in syscall () from /lib64/libc.so.6
#1  0x0000ffffee6c0fb8 in xshmfence_await () from /lib64/libxshmfence.so.1
```

**Comment by kaazoo** [comment]
same with muvm 0.2.0

**Comment by whitebelyash** [comment]
Seems like hangs aren't present with zink driver (instead of native opengl).
So, doing `export MESA_LOADER_DRIVER_OVERRIDE=zink` should workaround this bug before it gets fixed.
![Screenshot From 2024-12-21 04-42-57](https://github.com/user-attachments/assets/86024f8b-e3d5-4e3f-86e0-3720725f90c2)
