### ISSUE TITLE
Error creating the Kvm object: Error(2)

### ISSUE THREAD

**Issue by tiehfood** [AsahiLinux/muvm#99]
Could I run this inside an LXC container?
I tried to run it in an Ubuntu 24.04 container. I compiled everything from source but get the following error message

```
ubuntu@test24:~$ RUST_LOG=debug RUST_BACKTRACE=1 muvm -f=/home/ubuntu/.fex-emu/RootFS/Ubuntu_24_04.sqsh bash
[2024-11-03T16:23:24Z DEBUG muvm] sched_setaffinity cpuset=CpuSet { cpu4, cpu5, cpu6, cpu7, cpu8, cpu9, cpu10, cpu11 }
[2024-11-03T16:23:24Z DEBUG muvm] krun_set_vm_config num_vcpus=8 ram_mib=25296
[2024-11-03T16:23:24Z DEBUG muvm::net] passing fd to passt fd=6
[2024-11-03T16:23:24Z DEBUG muvm::env] env vars env={"PATH": "/home/ubuntu/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "RUST_LOG": "debug", "MESA_LOADER_DRIVER_OVERRIDE": "asahi"}
thread '<unnamed>' panicked at src/vmm/src/linux/vstate.rs:417:30:
Error creating the Kvm object: Error(2)
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: vmm::linux::vstate::KvmContext::new
   4: krun_start_enter
   5: muvm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0xffff8b98f970 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb96435122ab7425b
   1:     0xffff8b84acf4 - core::fmt::write::h7c561ca7c8433f95
   2:     0xffff8b96d154 - std::io::Write::write_fmt::hf7d9a5a24b8e20d9
   3:     0xffff8b993514 - std::panicking::default_hook::{{closure}}::hede73113e98cf4b8
   4:     0xffff8b9943a8 - std::panicking::rust_panic_with_hook::hd458a5a67c8fc44a
   5:     0xffff8b993e14 - std::panicking::begin_panic_handler::{{closure}}::h4b3f096abbb4f13c
   6:     0xffff8b993db8 - std::sys::backtrace::__rust_end_short_backtrace::hf33da5adf3f15f28
   7:     0xffff8b993dac - rust_begin_unwind
   8:     0xffff8b812e54 - core::panicking::panic_nounwind_fmt::hf40a377f5ad5ac1e
   9:     0xffff8b812eb0 - core::panicking::panic_nounwind::h10b041b95427555f
  10:     0xffff8b812e68 - core::panicking::panic_cannot_unwind::hdc935726f7d7d43e
  11:     0xffff8b82b8ac - krun_start_enter
  12:     0xaaab81097928 - muvm::main::hd91100403451d664
  13:     0xaaab8109f710 - std::sys::backtrace::__rust_begin_short_backtrace::h46cb60d843efcd72
  14:     0xaaab8109f688 - std::rt::lang_start::{{closure}}::h37c3311afe1bf562
  15:     0xaaab810f5e4c - std::rt::lang_start_internal::h61a6df977a78ceb9
  16:     0xaaab81098348 - main
  17:     0xffff8b5484c4 - <unknown>
  18:     0xffff8b548598 - __libc_start_main
  19:     0xaaab810951f0 - _start
  20:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
Aborted
```

My goal is to run an x86_64 application with FEX-Emu inside an LXC container.

**Comment by tiehfood** [comment]
Could muvm be executed headless in CLI only?

**Comment by slp** [comment]
Do you have access to `/dev/kvm` in the container? You'll also need access to other devices, such as `/dev/dri/...`.

**Comment by tiehfood** [comment]
I will check, thanks 👍🏼

**Comment by tiehfood** [comment]
It seems this was the problem, thank you 👍
